local colors = require("nvtheme").colors

local highlights = {
	BlinkCmpMenu = { bg = colors.black },
	BlinkCmpMenuBorder = { fg = colors.grey_fg },
	BlinkCmpMenuSelection = { link = "PmenuSel", bold = true },
	BlinkCmpScrollBarThumb = { bg = colors.grey },
	BlinkCmpScrollBarGutter = { bg = colors.black2 },
	BlinkCmpLabel = { fg = colors.white },
	BlinkCmpLabelDeprecated = { fg = colors.red, strikethrough = true },
	BlinkCmpLabelMatch = { fg = colors.blue, bold = true },
	BlinkCmpLabelDetail = { fg = colors.light_grey },
	BlinkCmpLabelDescription = { fg = colors.light_grey },
	BlinkCmpSource = { fg = colors.grey_fg },
	BlinkCmpGhostText = { fg = colors.grey_fg },
	BlinkCmpDoc = { bg = colors.black },
	BlinkCmpDocBorder = { fg = colors.grey_fg },
	BlinkCmpDocSeparator = { fg = colors.grey },
	BlinkCmpDocCursorLine = { bg = colors.one_bg },
	BlinkCmpSignatureHelp = { bg = colors.black },
	BlinkCmpSignatureHelpBorder = { fg = colors.grey_fg },
	BlinkCmpSignatureHelpActiveParameter = { fg = colors.blue, bold = true },
	BlinkCmdKindConstant = { fg = colors.orange },
	BlinkCmdKindFunction = { fg = colors.teal },
	BlinkCmdKindIdentifier = { fg = colors.red },
	BlinkCmdKindField = { fg = colors.teal },
	BlinkCmdKindVariable = { fg = colors.pink },
	BlinkCmdKindSnippet = { fg = colors.red },
	BlinkCmdKindText = { fg = colors.vibrant_green },
	BlinkCmdKindStructure = { fg = colors.pink },
	BlinkCmdKindType = { fg = colors.yellow },
	BlinkCmdKindKeyword = { fg = colors.one_bg3 },
	BlinkCmdKindMethod = { fg = colors.teal },
	BlinkCmdKindConstructor = { fg = colors.blue },
	BlinkCmdKindFolder = { fg = colors.one_bg3 },
	BlinkCmdKindModule = { fg = colors.yellow },
	BlinkCmdKindProperty = { fg = colors.red },
	BlinkCmdKindEnum = { fg = colors.blue },
	BlinkCmdKindUnit = { fg = colors.pink },
	BlinkCmdKindClass = { fg = colors.teal },
	BlinkCmdKindFile = { fg = colors.one_bg3 },
	BlinkCmdKindInterface = { fg = colors.green },
	BlinkCmdKindColor = { fg = colors.white },
	BlinkCmdKindReference = { fg = colors.grey_fg2 },
	BlinkCmdKindEnumMember = { fg = colors.purple },
	BlinkCmdKindStruct = { fg = colors.pink },
	BlinkCmdKindValue = { fg = colors.cyan },
	BlinkCmdKindEvent = { fg = colors.yellow },
	BlinkCmdKindOperator = { fg = colors.grey_fg2 },
	BlinkCmdKindTypeParameter = { fg = colors.red },
	BlinkCmdKindCopilot = { fg = colors.green },
	BlinkCmdKindCodeium = { fg = colors.vibrant_green },
	BlinkCmdKindTabNine = { fg = colors.baby_pink },
	BlinkCmdKindSuperMaven = { fg = colors.yellow },
}

return highlights
