local colors = require("nvtheme").colors
local base16 = require("nvtheme").base_16

local highlights = {
	BlinkCmpMenu = { bg = colors.black },
	BlinkCmpMenuBorder = { fg = colors.grey_fg },
	BlinkCmpMenuSelection = { link = "PmenuSel", bold = true },
	BlinkCmpScrollBarThumb = { bg = colors.grey },
	BlinkCmpScrollBarGutter = { bg = colors.black2 },
	BlinkCmpLabel = { fg = colors.white },
	BlinkCmpLabelDeprecated = { fg = colors.red, strikethrough = true },
	BlinkCmpLabelMatch = { fg = colors.blue, bold = true },
	BlinkCmpLabelDetail = { fg = colors.light_grey },
	BlinkCmpLabelDescription = { fg = colors.light_grey },
	BlinkCmpSource = { fg = colors.grey_fg },
	BlinkCmpGhostText = { fg = colors.grey_fg },
	BlinkCmpDoc = { bg = colors.black },
	BlinkCmpDocBorder = { fg = colors.grey_fg },
	BlinkCmpDocSeparator = { fg = colors.grey },
	BlinkCmpDocCursorLine = { bg = colors.one_bg },
	BlinkCmpSignatureHelp = { bg = colors.black },
	BlinkCmpSignatureHelpBorder = { fg = colors.grey_fg },
	BlinkCmpSignatureHelpActiveParameter = { fg = colors.blue, bold = true },
	BlinkCmpKindConstant = base16.base09,
	BlinkCmpKindFunction = base16.base0D,
	BlinkCmpKindIdentifier = base16.base08,
	BlinkCmpKindField = base16.base08,
	BlinkCmpKindVariable = base16.base0E,
	BlinkCmpKindSnippet = colors.red,
	BlinkCmpKindText = base16.base0B,
	BlinkCmpKindStructure = base16.base0E,
	BlinkCmpKindType = base16.base0A,
	BlinkCmpKindKeyword = base16.base07,
	BlinkCmpKindMethod = base16.base0D,
	BlinkCmpKindConstructor = colors.blue,
	BlinkCmpKindFolder = base16.base07,
	BlinkCmpKindModule = base16.base0A,
	BlinkCmpKindProperty = base16.base08,
	BlinkCmpKindEnum = colors.blue,
	BlinkCmpKindUnit = base16.base0E,
	BlinkCmpKindClass = colors.teal,
	BlinkCmpKindFile = base16.base07,
	BlinkCmpKindInterface = colors.green,
	BlinkCmpKindColor = colors.white,
	BlinkCmpKindReference = base16.base05,
	BlinkCmpKindEnumMember = colors.purple,
	BlinkCmpKindStruct = base16.base0E,
	BlinkCmpKindValue = colors.cyan,
	BlinkCmpKindEvent = colors.yellow,
	BlinkCmpKindOperator = base16.base05,
	BlinkCmpKindTypeParameter = base16.base08,
	BlinkCmpKindCopilot = colors.green,
	BlinkCmpKindCodeium = colors.vibrant_green,
	BlinkCmpKindTabNine = colors.baby_pink,
	BlinkCmpKindSuperMaven = colors.yellow,
}

return highlights
