local colors = require("nvtheme").colors
local base16 = require("nvtheme").base16

local highlights = {
	BlinkCmpMenu = { bg = colors.black },
	BlinkCmpMenuBorder = { fg = colors.grey_fg },
	BlinkCmpMenuSelection = { link = "PmenuSel", bold = true },
	BlinkCmpScrollBarThumb = { bg = colors.grey },
	BlinkCmpScrollBarGutter = { bg = colors.black2 },
	BlinkCmpLabel = { fg = colors.white },
	BlinkCmpLabelDeprecated = { fg = colors.red, strikethrough = true },
	BlinkCmpLabelMatch = { fg = colors.blue, bold = true },
	BlinkCmpLabelDetail = { fg = colors.light_grey },
	BlinkCmpLabelDescription = { fg = colors.light_grey },
	BlinkCmpSource = { fg = colors.grey_fg },
	BlinkCmpGhostText = { fg = colors.grey_fg },
	BlinkCmpDoc = { bg = colors.black },
	BlinkCmpDocBorder = { fg = colors.grey_fg },
	BlinkCmpDocSeparator = { fg = colors.grey },
	BlinkCmpDocCursorLine = { bg = colors.one_bg },
	BlinkCmpSignatureHelp = { bg = colors.black },
	BlinkCmpSignatureHelpBorder = { fg = colors.grey_fg },
	BlinkCmpSignatureHelpActiveParameter = { fg = colors.blue, bold = true },

	BlinkCmpKindConstant = { fg = base16.base09 },
	BlinkCmpKindFunction = { fg = base16.base0D },
	BlinkCmpKindIdentifier = { fg = base16.base08 },
	BlinkCmpKindField = { fg = base16.base08 },
	BlinkCmpKindVariable = { fg = base16.base0E },
	BlinkCmpKindSnippet = { fg = colors.red },
	BlinkCmpKindText = { fg = base16.base0B },
	BlinkCmpKindStructure = { fg = base16.base0E },
	BlinkCmpKindType = { fg = base16.base0A },
	BlinkCmpKindKeyword = { fg = base16.base07 },
	BlinkCmpKindMethod = { fg = base16.base0D },
	BlinkCmpKindConstructor = { fg = colors.blue },
	BlinkCmpKindFolder = { fg = base16.base07 },
	BlinkCmpKindModule = { fg = base16.base0A },
	BlinkCmpKindProperty = { fg = base16.base08 },
	BlinkCmpKindEnum = { fg = colors.blue },
	BlinkCmpKindUnit = { fg = base16.base0E },
	BlinkCmpKindClass = { fg = colors.teal },
	BlinkCmpKindFile = { fg = base16.base07 },
	BlinkCmpKindInterface = { fg = colors.green },
	BlinkCmpKindColor = { fg = colors.white },
	BlinkCmpKindReference = { fg = base16.base05 },
	BlinkCmpKindEnumMember = { fg = colors.purple },
	BlinkCmpKindStruct = { fg = base16.base0E },
	BlinkCmpKindValue = { fg = colors.cyan },
	BlinkCmpKindEvent = { fg = colors.yellow },
	BlinkCmpKindOperator = { fg = base16.base05 },
	BlinkCmpKindTypeParameter = { fg = base16.base08 },
	BlinkCmpKindCopilot = { fg = colors.green },
	BlinkCmpKindCodeium = { fg = colors.vibrant_green },
	BlinkCmpKindTabNine = { fg = colors.baby_pink },
	BlinkCmpKindSuperMaven = { fg = colors.yellow },
}

return highlights
