local colors = require("nvtheme").colors

return {
	Added = { fg = colors.green },
	Removed = { fg = colors.red },
	Changed = { fg = colors.yellow },
	MatchWord = { bg = colors.grey, fg = colors.white },
	Pmenu = { bg = colors.one_bg },
	PmenuSbar = { bg = colors.one_bg },
	PmenuSel = { bg = colors.pmenu_bg, fg = colors.black },
	PmenuThumb = { bg = colors.grey },
	MatchParen = { link = "MatchWord" },
	Comment = { fg = colors.light_grey },
	CursorLineNr = { fg = colors.white },
	LineNr = { fg = colors.grey },
	FloatBorder = { fg = colors.blue },
	FloatTitle = { fg = colors.white, bg = colors.grey },
	NormalFloat = { bg = colors.darker_black },
	NvimInternalError = { fg = colors.red },
	WinSeparator = { fg = colors.line },
	Normal = { fg = colors.grey_fg2, bg = colors.black },
	DevIconDefault = { fg = colors.red },
	Debug = { fg = colors.red },
	Directory = { fg = colors.teal },
	Error = { fg = colors.black, bg = colors.red },
	ErrorMsg = { fg = colors.red, bg = colors.black },
	Exception = { fg = colors.red },
	FoldColumn = { bg = "none" },
	Folded = { fg = colors.light_grey, bg = colors.black2 },
	IncSearch = { fg = colors.one_bg2, bg = colors.orange },
	Macro = { fg = colors.red },
	ModeMsg = { fg = colors.green },
	MoreMsg = { fg = colors.green },
	Question = { fg = colors.teal },
	Search = { fg = colors.one_bg2, bg = colors.yellow },
	Substitute = { fg = colors.one_bg2, bg = colors.yellow },
	SpecialKey = { fg = colors.grey_fg },
	TooLong = { fg = colors.red },
	Visual = { bg = colors.one_bg3 },
	VisualNOS = { fg = colors.red },
	WarningMsg = { fg = colors.red },
	WildMenu = { fg = colors.red, bg = colors.yellow },
	Title = { fg = colors.teal },
	Conceal = { bg = "NONE" },
	Cursor = { fg = colors.black, bg = colors.white },
	NonText = { fg = colors.grey_fg },
	SignColumn = { fg = colors.grey_fg },
	ColorColumn = { bg = colors.black2 },
	CursorColumn = { bg = colors.one_bg2 },
	CursorLine = { bg = colors.black2 },
	QuickFixLine = { bg = colors.one_bg2 },
	healthSuccess = { bg = colors.green, fg = colors.black },
	WinBar = { bg = "NONE" },
	WinBarNC = { bg = "NONE" },

	Boolean = { fg = colors.orange },
	Character = { fg = colors.red },
	Conditional = { fg = colors.dark_purple },
	Constant = { fg = colors.orange },
	Define = { fg = colors.dark_purple, sp = "none" },
	Delimiter = { fg = colors.red, bold = true },
	Float = { fg = colors.orange },
	Variable = { fg = colors.white },
	Function = { fg = colors.teal },
	Identifier = { fg = colors.red, sp = "none" },
	Include = { fg = colors.teal },
	Keyword = { fg = colors.dark_purple },
	Label = { fg = colors.yellow },
	Number = { fg = colors.orange },
	Operator = { fg = colors.white, sp = "none" },
	PreProc = { fg = colors.yellow },
	Repeat = { fg = colors.yellow },
	Special = { fg = colors.cyan },
	SpecialChar = { fg = colors.red, bold = true },
	Statement = { fg = colors.red },
	StorageClass = { fg = colors.yellow },
	String = { fg = colors.green },
	Structure = { fg = colors.dark_purple },
	Tag = { fg = colors.yellow },
	Todo = { fg = colors.yellow, bg = colors.one_bg2 },
	Type = { fg = colors.yellow, sp = "none" },
	Typedef = { fg = colors.yellow },
}
