local colors = require("nvtheme").colors

return {
	Added = { fg = colors.green },
	Removed = { fg = colors.red },
	Changed = { fg = colors.yellow },
	MatchWord = { bg = colors.grey, fg = colors.white },
	Pmenu = { bg = colors.one_bg },
	PmenuSbar = { bg = colors.one_bg },
	PmenuSel = { bg = colors.pmenu_bg, fg = colors.black },
	PmenuThumb = { bg = colors.grey },
	MatchParen = { link = "MatchWord" },
	Comment = { fg = colors.light_grey },
	CursorLineNr = { fg = colors.white },
	LineNr = { fg = colors.grey },
	FloatBorder = { fg = colors.blue },
	FloatTitle = { fg = colors.white, bg = colors.grey },
	NormalFloat = { bg = colors.darker_black },
	NvimInternalError = { fg = colors.red },
	WinSeparator = { fg = colors.line },
	Normal = { fg = colors.grey_fg2, bg = colors.black },
	DevIconDefault = { fg = colors.red },
	Debug = { fg = colors.red },
	Directory = { fg = colors.teal },
	Error = { fg = colors.black, bg = colors.red },
	ErrorMsg = { fg = colors.red, bg = colors.black },
	Exception = { fg = colors.red },
	FoldColumn = { bg = "none" },
	Folded = { fg = colors.light_grey, bg = colors.black2 },
	IncSearch = { fg = colors.one_bg2, bg = colors.orange },
	Macro = { fg = colors.red },
	ModeMsg = { fg = colors.green },
	MoreMsg = { fg = colors.green },
	Question = { fg = colors.teal },
	Search = { fg = colors.one_bg2, bg = colors.yellow },
	Substitute = { fg = colors.one_bg2, bg = colors.yellow },
	SpecialKey = { fg = colors.grey_fg },
	TooLong = { fg = colors.red },
	Visual = { bg = colors.one_bg3 },
	VisualNOS = { fg = colors.red },
	WarningMsg = { fg = colors.red },
	WildMenu = { fg = colors.red, bg = colors.yellow },
	Title = { fg = colors.teal },
	Conceal = { bg = "NONE" },
	Cursor = { fg = colors.black, bg = colors.white },
	NonText = { fg = colors.grey_fg },
	SignColumn = { fg = colors.grey_fg },
	ColorColumn = { bg = colors.black2 },
	CursorColumn = { bg = colors.one_bg2 },
	CursorLine = { bg = colors.black2 },
	QuickFixLine = { bg = colors.one_bg2 },
	healthSuccess = { bg = colors.green, fg = colors.black },
	WinBar = { bg = "NONE" },
	WinBarNC = { bg = "NONE" },
}
